var recursive = require('recursive-readdir');
var winston = null;
var Command = require('ronin').Command;
var async = require('async');
var trash = require('trash');
var fs = require('fs');

var clean = require('../lib/clean');
var ALL_EXTENSIONS = clean.ALL_EXTENSIONS;
var EXTENSIONS = clean.EXTENSIONS;
    
var CleanCommand = module.exports = Command.extend({
    use: ['winston', 'find-repository-root'],
    
    desc: 'Remove files generated by pdflatex and htlatex',

    options: {
        all: {
            type: 'boolean',
	    default: false
        },
	
        'delete': {
            type: 'boolean',
	    default: false
        }	
    },
    
    run: function (all, actuallyDelete) {
	var global = this.global;
	winston = global.winston;

	// Include more extenions if "--all" is given
	if (all) {
	    ALL_EXTENSIONS.forEach( function(e) {
		EXTENSIONS.push(e);
	    });
	}
	
	clean.determineFilesToClean( global.repository, function(err, filenames) {
	    if (filenames.length == 0)
		winston.info("Nothing to clean.");
	    else {
		if (!actuallyDelete) {
		    trash( filenames ).then( function() {
			winston.info("Moved " + filenames.length + " output files to the trash.");
		    });
		} else {
		    async.each( filenames, function( filename, callback ) {
			fs.unlink( filename, callback );
		    }, function(err) {
			if (err)
			    throw new Error(err);
			else
			    winston.info("Deleted " + filenames.length + " output files.");
		    });
		}
	    }
	});
    }
});
